Thanks to Biju Kunjummen https://github.com/bijukunjummen for most of the work. I have just updated it to RabbitMQ 3.8 (with Erlang 22.2 and CentOS 8.3)

This folder structure contains the Dockerfiles for building RabbitMQ cluster - the number of nodes are completely customizable using https://docs.docker.com/compose/[docker-compose] docker-compose.yml file.

Structure:
==========
There are 3 folders.

1. base - this is the base Dockerfile which builds on a CentOS image and installs the RabbitMQ binaries on the image
2. server - This builds on the base image and has the startup script for bring up a RabbitMQ server
4. cluster - This contains a https://docs.docker.com/compose/[docker-compose] definition file(docker-compose.yml) for brining up the rabbitmq cluster. Use `docker-compose up -d` to bring up the cluster.


Building the Images:
===============================
Just run the `build-images.sh` script to create the RabbitMQ docker container images.

Running the Cluster:
===============================
Once the images are built, boot up the cluster using the `docker-compose.yml` configuration provided in cluster folder:    

[source]
----
cd cluster
docker-compose up -d
----

By default 3 nodes are started up this way see `docker-compose.yml` 

If needed, additional nodes can be added to this file. If the entire cluster comes up, the management console can be accessed at http://<dockerip>:15672 and http://<dockerip>:15673 (also works for `localhost`)

The username/password are specified in `docker-compose.yml`: `myuser/mypass`

and the connection host should look like this: `dockerip:5672,dockerip:5673,dockerip:5674`


    
